# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

include:
  - project: "dhei/teams/hyperion/dev/src/foundation-build"
    file: "/pipelines/java-maven-docker-release-pipeline.yaml"
    ref: main
  - project: "dhei/teams/hyperion/dev/src/foundation-build"
    file: "/pipelines/opensource-pipeline.yaml"
    ref: main

variables:
  PUSH_TO_HARBOR: "true"
  MAVEN_ADD_OPTS: "-DskipTests"
