# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

include:
  - project: "dhei/teams/hyperion/dev/src/foundation-build"
    file: "/pipelines/java-maven-docker-release-pipeline.yaml"
    ref: 16.1.0
  - project: "dhei/teams/hyperion/dev/src/foundation-build"
    file: "/pipelines/opensource-pipeline.yaml"
    ref: 16.1.0
    rules:
      - if: $CI_PROJECT_NAME == "stargate-issuer-service"

variables:
  PUSH_TO_HARBOR: "true"
  MAVEN_ADD_OPTS: "-DskipTests"
  GITHUB_PROJECT_PATH: "telekom/stargate-issuer-service"
  GITLAB_PROJECT_PATH: "dhei/teams/hyperion/dev/src/issuer-service"
  GITLAB_SOURCE_BRANCH: main