# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

FROM maven:3.9-eclipse-temurin-17 AS build
RUN mkdir -p /usr/app
WORKDIR /usr/app
ADD . /usr/app

RUN mvn -f /usr/app/pom.xml clean package -DskipTests


FROM eclipse-temurin:17-jre

USER 1000:1000

EXPOSE 8081

COPY --from=build /usr/app/target/*.jar /usr/share/app.jar

WORKDIR /usr/share/

CMD java $JVM_OPTS -jar /usr/share/app.jar