# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

FROM alpine:3

RUN apk add --no-cache \
    bash \
    curl \
    jq \
    openssl \
    sed \
    base64 \
    uuidgen \
    perl-utils \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /opt/app

COPY ./createKeys-alpine.sh /opt/app/createKeys.sh

RUN chmod +x /opt/app/createKeys.sh

WORKDIR /opt/app
